### ISSUE TITLE
This is more of a question 

### ISSUE THREAD

**Issue by NeoPrint3D** [AkileshAro/chat-client#3]
Let's say for a production environment would storing the users in a variable be a good idea or use a database for it?

**Comment by AkileshRao** [comment]
To persist your user data, you'll need some form of external storage. It could be inside your file system or a separate database altogether. Storing data in application variables is just too risky and exposes you to a host of security issues. Having a separate data layer is what I'd recommend.

**Comment by NeoPrint3D** [comment]
Thanks so much
